export { default as CreateUser } from "./CreateUser";
export { default as UpdateUser } from "./UpdateUser";
export { default as DeleteUser } from "./DeleteUser";
export { default as DataTable } from "./DataTable";
export { default as Loader } from "./Loader";
export { default as Modal } from "./Modal";
export { default as Pagination } from "./Pagination";
export { default as Search } from "./Search";
export { default as Swal } from "./Swal";